# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dump.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndump.proto\x12\x04\x44ump\"\x1f\n\x06String\x12\x15\n\rstring_stream\x18\x05 \x01(\t\"0\n\nArrayFloat\x12\x14\n\x0c\x66loat_stream\x18\x05 \x03(\x02\x12\x0c\n\x04\x64ims\x18\x06 \x03(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dump_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRING._serialized_start=20
  _STRING._serialized_end=51
  _ARRAYFLOAT._serialized_start=53
  _ARRAYFLOAT._serialized_end=101
# @@protoc_insertion_point(module_scope)
