
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-30T14:22:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9ce16e635051df2f276badf2a20cf111b072446",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
