
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-27T19:55:40+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f4e89b2b9db0d82e8e3081cbefcbed687f5f290",
 "version": "1.2.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
