VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('26')
VERSION_HOUR = int('23')
VERSION_MINUTE = int('08')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306262308
version_date = '2023/06/26 23:08'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
