
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-28T04:59:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc7b48b11fc3d5e5241a1b72ae019e0fadf836f3",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
