# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/abc/dfdm/00_meta.ipynb.

# %% auto 0
__all__ = ['MetaDataFrameDataModule']

# %% ../../../nbs/abc/dfdm/00_meta.ipynb 3
from abc import ABCMeta, abstractmethod

from beartype.typing import (
    Tuple, Optional,
)

# %% ../../../nbs/abc/dfdm/00_meta.ipynb 4
from ..dfds.base import BaseDataFrameDataset

# %% ../../../nbs/abc/dfdm/00_meta.ipynb 6
class MetaDataFrameDataModule(ABCMeta): 
    __args__: Tuple[BaseDataFrameDataset, ]

    def __instancecheck__(cls, instance):
        return hasattr(instance, 'df')
     
    @abstractmethod
    def prepare_data(self) -> None:
        pass

    @abstractmethod
    def setup(self, stage: Optional[str]=None) -> None:
        pass   
