
class QuickbaseClient:
    username: str = ...
    password: str = ...
    realmhost: str = ...
    base_url: str = ...
    user_token: str = ...
    timeout: int = ...
    database: str = ...
    def __init__(self, credentials: dict[str, str], timeout: int = 90, database: str | None = None) -> None:
        """
        Client for Quickbase API
        :param credentials: (dict) A dictionary of credentials
        :param timeout: (int) The number of seconds to wait before timing out a request
        :param database: (str or None) The Quickbase database ID
        """
        ...
