# -*- coding: utf-8 -*-

"""
    pagarmecoreapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from pagarmecoreapi.api_helper import APIHelper


class PlansControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(PlansControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.plans

    # Gets all plans
    def test_test_get_plans(self):
        # Parameters for the API call
        page = None
        size = None
        name = None
        status = None
        billing_type = None
        created_since = None
        created_until = None

        # Perform the API call through the SDK function
        result = self.controller.get_plans(page, size, name, status, billing_type, created_since, created_until)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


