# -*- coding: utf-8 -*-

"""
    pagarmecoreapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from pagarmecoreapi.api_helper import APIHelper


class TransfersControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(TransfersControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.transfers

    # Gets all transfers
    def test_test_get_transfers_1(self):

        # Perform the API call through the SDK function
        result = self.controller.get_transfers_1()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


