
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-28T19:14:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "abb84103aea0bb5ead9bfe7fd32af7f77c9681d2",
 "version": "7.30.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
