# Generated by Django 3.2.9 on 2021-11-09 18:51

from django.db import migrations, models
import django_q3c.indexes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name='position',
            index=django_q3c.indexes.Q3CIndex(dec_col='dec', name='q3c_index', ra_col='ra'),
        ),
    ]
