
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-29T14:34:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf177852ac8ae660150edac513ea52c023a5dbab",
 "version": "2.10.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
