# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aibabyllmclient.core import tongos_service_pb2 as core_dot_tongos__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class TongOSUnitStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SessionInitialization = channel.unary_unary(
                '/bigai.tongos.core.TongOSUnit/SessionInitialization',
                request_serializer=core_dot_tongos__service__pb2.SessionInitializationRequest.SerializeToString,
                response_deserializer=core_dot_tongos__service__pb2.SessionInitializationResponse.FromString,
                )
        self.StreamingMediaProcess = channel.stream_stream(
                '/bigai.tongos.core.TongOSUnit/StreamingMediaProcess',
                request_serializer=core_dot_tongos__service__pb2.StreamingMediaRequest.SerializeToString,
                response_deserializer=core_dot_tongos__service__pb2.MediaResponse.FromString,
                )
        self.MediaProcess = channel.unary_unary(
                '/bigai.tongos.core.TongOSUnit/MediaProcess',
                request_serializer=core_dot_tongos__service__pb2.MediaRequest.SerializeToString,
                response_deserializer=core_dot_tongos__service__pb2.MediaResponse.FromString,
                )
        self.GetConstract = channel.unary_unary(
                '/bigai.tongos.core.TongOSUnit/GetConstract',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=core_dot_tongos__service__pb2.ProcessorContract.FromString,
                )


class TongOSUnitServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SessionInitialization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingMediaProcess(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MediaProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConstract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TongOSUnitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SessionInitialization': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionInitialization,
                    request_deserializer=core_dot_tongos__service__pb2.SessionInitializationRequest.FromString,
                    response_serializer=core_dot_tongos__service__pb2.SessionInitializationResponse.SerializeToString,
            ),
            'StreamingMediaProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingMediaProcess,
                    request_deserializer=core_dot_tongos__service__pb2.StreamingMediaRequest.FromString,
                    response_serializer=core_dot_tongos__service__pb2.MediaResponse.SerializeToString,
            ),
            'MediaProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.MediaProcess,
                    request_deserializer=core_dot_tongos__service__pb2.MediaRequest.FromString,
                    response_serializer=core_dot_tongos__service__pb2.MediaResponse.SerializeToString,
            ),
            'GetConstract': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConstract,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=core_dot_tongos__service__pb2.ProcessorContract.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bigai.tongos.core.TongOSUnit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TongOSUnit(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SessionInitialization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bigai.tongos.core.TongOSUnit/SessionInitialization',
            core_dot_tongos__service__pb2.SessionInitializationRequest.SerializeToString,
            core_dot_tongos__service__pb2.SessionInitializationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamingMediaProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/bigai.tongos.core.TongOSUnit/StreamingMediaProcess',
            core_dot_tongos__service__pb2.StreamingMediaRequest.SerializeToString,
            core_dot_tongos__service__pb2.MediaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MediaProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bigai.tongos.core.TongOSUnit/MediaProcess',
            core_dot_tongos__service__pb2.MediaRequest.SerializeToString,
            core_dot_tongos__service__pb2.MediaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConstract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bigai.tongos.core.TongOSUnit/GetConstract',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            core_dot_tongos__service__pb2.ProcessorContract.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
