VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('27')
VERSION_HOUR = int('01')
VERSION_MINUTE = int('30')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306270130
version_date = '2023/06/27 01:30'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
