# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.03.1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200127_zios import InlineResponse200127Zios  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200127Zios(unittest.TestCase):
    """InlineResponse200127Zios unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200127Zios(self):
        """Test InlineResponse200127Zios"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200127_zios.InlineResponse200127Zios()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
