# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.03.1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20039_node_resources import InlineResponse20039NodeResources  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20039NodeResources(unittest.TestCase):
    """InlineResponse20039NodeResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20039NodeResources(self):
        """Test InlineResponse20039NodeResources"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20039_node_resources.InlineResponse20039NodeResources()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
