
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-28T17:13:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dffa960709031d0826d7088cdd052281b2bc41da",
 "version": "0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
