
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-27T15:43:45+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f62d97f64d900291f71f03bd01566a33a39e359",
 "version": "1.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
