# Generated by Django 4.2.2 on 2023-06-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_fomantic_ui', '0001_squashed_0052_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordionsection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tabpluginmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
