
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-27T11:02:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "acd6c529b2291797ed509c61ac7d4e1f13ec4868",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
