# coding: utf-8

"""
    Workspace Data Service

    This page lists current APIs. As of v0.2, all APIs are subject to change without notice.   # noqa: E501

    The version of the OpenAPI document: v0.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from wds_client.configuration import Configuration


class BackupResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'backup_status': 'bool',
        'message': 'str'
    }

    attribute_map = {
        'backup_status': 'backupStatus',
        'message': 'message'
    }

    def __init__(self, backup_status=None, message=None, local_vars_configuration=None):  # noqa: E501
        """BackupResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._backup_status = None
        self._message = None
        self.discriminator = None

        if backup_status is not None:
            self.backup_status = backup_status
        if message is not None:
            self.message = message

    @property
    def backup_status(self):
        """Gets the backup_status of this BackupResponse.  # noqa: E501

        status of backup  # noqa: E501

        :return: The backup_status of this BackupResponse.  # noqa: E501
        :rtype: bool
        """
        return self._backup_status

    @backup_status.setter
    def backup_status(self, backup_status):
        """Sets the backup_status of this BackupResponse.

        status of backup  # noqa: E501

        :param backup_status: The backup_status of this BackupResponse.  # noqa: E501
        :type: bool
        """

        self._backup_status = backup_status

    @property
    def message(self):
        """Gets the message of this BackupResponse.  # noqa: E501

        message regarding backup status  # noqa: E501

        :return: The message of this BackupResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this BackupResponse.

        message regarding backup status  # noqa: E501

        :param message: The message of this BackupResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BackupResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BackupResponse):
            return True

        return self.to_dict() != other.to_dict()
