VERSION_YEAR = 2023
VERSION_MONTH = int('06')
VERSION_DAY = int('27')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('34')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202306271034
version_date = '2023/06/27 10:34'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
