# Generated by Django 4.0.2 on 2022-02-14 18:45

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="The name of the Wine Trail as you'd like it to be seen by the public", max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='The name of the Wine Trail  as it will appear in URLs e.g http://domain.com/wineries/pub-crawl/', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Wine Trail',
                'verbose_name_plural': 'Wine Trails',
            },
        ),
        migrations.RemoveField(
            model_name='winery',
            name='trail_a_part_of',
        ),
        migrations.AddField(
            model_name='winery',
            name='trail_a_part_of',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='goldbook.WineTrail', verbose_name='Trail a part of'),
        ),
    ]
