# Generated by Django 4.0.2 on 2022-02-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0002_winetrail_remove_winery_trail_a_part_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="The name of the AVA as you'd like it to be seen by the public", max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='The name of the AVA  as it will appear in URLs e.g http://domain.com/wineries/ava/blue-ridge/', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'AVA',
                'verbose_name_plural': 'AVAs',
            },
        ),
        migrations.AlterField(
            model_name='winery',
            name='ava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='goldbook.ava', verbose_name='AVA'),
        ),
    ]
