# Generated by Django 4.0.2 on 2022-02-17 19:45

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0003_ava_alter_winery_ava'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='food_truck',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='food_truck', to='goldbook.Occurrence', verbose_name='Food Truck Available?'),
        ),
    ]
