# Generated by Django 4.0.2 on 2022-02-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0004_winery_food_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='quantity_limit_on_walkin_party_size',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Quantity limit on walk-in party size?'),
        ),
    ]
