# Generated by Django 4.0.2 on 2022-02-17 20:25

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0005_winery_quantity_limit_on_walkin_party_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsFromSeating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text="The name of the View as you'd like it to be seen by the public", max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='The name of the view as it will appear in URLs e.g http://domain.com/wineries/northern-va/lakeviews/', max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'View From Seating',
                'verbose_name_plural': 'Seating Views',
            },
        ),
        migrations.AddField(
            model_name='winery',
            name='tastingroom_views',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='goldbook.ViewsFromSeating', verbose_name='Views from Tasting Room seating?'),
        ),
    ]
