# Generated by Django 4.0.2 on 2022-02-17 20:48

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0006_viewsfromseating_winery_tastingroom_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='ceremony_views',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='ceremony_views', to='goldbook.ViewsFromSeating', verbose_name='Views from Ceremony?'),
        ),
        migrations.AddField(
            model_name='winery',
            name='designated_reception_hall_views',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='reception_hall_views', to='goldbook.ViewsFromSeating', verbose_name='Views from Reception Hall?'),
        ),
    ]
