# Generated by Django 4.1.5 on 2023-06-21 17:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailgeowidget.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('goldbook', '0007_winery_ceremony_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winery',
            name='address',
            field=wagtail.fields.StreamField([('map_struct', wagtail.blocks.StructBlock([('address', wagtailgeowidget.blocks.GeoAddressBlock(required=True)), ('map', wagtailgeowidget.blocks.GeoBlock(address_field='address'))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='winery',
            name='tasting_room_address',
            field=wagtail.fields.StreamField([('map_struct', wagtail.blocks.StructBlock([('address', wagtailgeowidget.blocks.GeoAddressBlock(required=False)), ('map', wagtailgeowidget.blocks.GeoBlock(address_field='tasting_room_address'))]))], blank=True, use_json_field=True),
        ),
    ]
