# Generated by Django 4.2.2 on 2023-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis', '0020_coffeewarehouse_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='confirmed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmed at'),
        ),
        migrations.AddField(
            model_name='offer',
            name='confirmed_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Confirmed by'),
        ),
    ]
