
ALPHAVANTAGE = 'ALPHAVANTAGE'
QUANDL = 'QUANDL'

EXCHANGES_LIST = [ALPHAVANTAGE, QUANDL]

POSTGRES = 'POSTGRES'

# REST OP
GET = 'GET'
POST = 'POST'

# available methods / tables
REFRESH_SYMBOL = 'REFRESH_SYMBOL'
REFRESH_SYMBOL_LOOKUP = 'REFRESH_SYMBOL_LOOKUP'

SYMBOL = 'SYMBOL'
EXCHANGE = 'EXCHANGE'
BASE_SYMBOL = 'BASE_SYMBOL'
QUOTE_SYMBOL = 'QUOTE_SYMBOL'

RAW = 'RAW'

# db schema
TABLE = 'tb_'
