# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\x1a\x1bgoogle/protobuf/empty.proto\"P\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12!\n\x06status\x18\x04 \x01(\x0e\x32\x11.users.UserStatus\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05*?\n\nUserStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07OFFLINE\x10\x01\x12\x08\n\x04\x42USY\x10\x02\x12\r\n\tAVAILABLE\x10\x03\x32\xa1\x01\n\x05Users\x12,\n\x07GetUser\x12\x12.users.UserRequest\x1a\x0b.users.User\"\x00\x12\x35\n\nCreateUser\x12\x0b.users.User\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12\x33\n\x08GetUsers\x12\x16.google.protobuf.Empty\x1a\x0b.users.User\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERSTATUS']._serialized_start=160
  _globals['_USERSTATUS']._serialized_end=223
  _globals['_USER']._serialized_start=51
  _globals['_USER']._serialized_end=131
  _globals['_USERREQUEST']._serialized_start=133
  _globals['_USERREQUEST']._serialized_end=158
  _globals['_USERS']._serialized_start=226
  _globals['_USERS']._serialized_end=387
# @@protoc_insertion_point(module_scope)
