
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-26T13:53:56-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8041c4e2e7a1392e2383353a74c0f548ca4c050",
 "version": "2.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
