# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/abc/mock/00_meta.ipynb.

# %% auto 0
__all__ = ['MetaMock']

# %% ../../../nbs/abc/mock/00_meta.ipynb 3
from abc import ABCMeta, abstractmethod
from dataclasses import dataclass

# %% ../../../nbs/abc/mock/00_meta.ipynb 4
from ...types import DataFrame

# %% ../../../nbs/abc/mock/00_meta.ipynb 7
class MetaMock(ABCMeta):
    @abstractmethod
    def setup(self) -> DataFrame:
        '''Function were code to produce the mock data is written'''
        pass
