
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-30T15:21:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "38c8cadcbd1e53ceca9ab64e0b0e168ebb47b846",
 "version": "2.0.0a15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
