# Generated by Django 4.1.5 on 2023-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0006_rename_legend_certificate_body_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='UNQ_certificates_key',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='key',
        ),
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.IntegerField(choices=[(0, 'Taxes'), (1, 'Commercial'), (2, 'Partners'), (3, 'Account Statements')], default=0, help_text='Document category', verbose_name='Category'),
        ),
    ]
