# Generated by Django 4.1.5 on 2023-02-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0007_remove_certificate_unq_certificates_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='customer_type',
            field=models.IntegerField(choices=[(0, 'Not bound'), (1, 'Customer'), (2, 'Partner')], default=0, help_text='Minimal customer type required for this document.', verbose_name='Customer type'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='category',
            field=models.IntegerField(choices=[(0, 'Taxes'), (1, 'Commercial'), (2, 'Partners'), (3, 'Account Statements'), (4, 'Farms')], default=0, help_text='Document category', verbose_name='Category'),
        ),
    ]
