# Generated by Django 4.1.5 on 2023-02-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0009_certificate_signed_alter_certificate_cycle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Text that is located in the footer of the certificate', verbose_name='Footer text'),
        ),
    ]
