# Generated by Django 4.1.7 on 2023-03-16 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zb_repository', '0002_document_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oasis_certs', '0010_alter_certificate_footer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('year', models.IntegerField()),
                ('period', models.IntegerField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oasis_certs.certificate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zb_repository.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
