# Generated by Django 4.1.7 on 2023-03-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0011_certificatefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatefile',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='certificatefile',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
