#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2302-80-gef0e17c5"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2302
#define NETGEN_VERSION_TWEAK 80
#define NETGEN_VERSION_HASH "gef0e17c5"
#endif // NETGEN_VERSION_HPP_INCLUDED
