
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-27T18:05:43-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "65eb04533df4d34d8c55ba2e8bae6ac1f24b2781",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
