# Generated by Django 4.2.1 on 2023-06-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis', '0019_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeewarehouse',
            name='city_name',
            field=models.CharField(max_length=150, null=True, verbose_name='City'),
        ),
    ]
