# coding: utf-8

"""
    Brainrex API

    The Brainrex API is a collection of analytics tools and data integrations made for blockchain developers. In particular we offer Natural Language Processing and Anomaly detection algorithms that have been fine tune to understand text data and time series in the domain speficic setting of cryptocurrency and blockchain technology.  # noqa: E501

    OpenAPI spec version: 1.0.3-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import brainrex
from brainrex.models.exchange_assets_response import ExchangeAssetsResponse  # noqa: E501
from brainrex.rest import ApiException


class TestExchangeAssetsResponse(unittest.TestCase):
    """ExchangeAssetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExchangeAssetsResponse(self):
        """Test ExchangeAssetsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = brainrex.models.exchange_assets_response.ExchangeAssetsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
