
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-27T14:56:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "befc5a66f72406ec1c1867462bd4001279a4f0da",
 "version": "0.0.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
