# Generated by Django 4.1.5 on 2023-02-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name that appare', max_length=80, verbose_name='Certificate name')),
                ('key', models.CharField(help_text='Key to call the query', max_length=20, verbose_name='Key to call back')),
                ('legend', models.TextField(help_text='Text that will be', verbose_name='Certificate text')),
                ('issue_date', models.DateField(blank=True, help_text='Issue date', null=True, verbose_name='Issue date')),
                ('query_text', models.TextField(help_text='Query to be executed', verbose_name='Query text')),
                ('template', models.CharField(help_text='Template to use', max_length=150, verbose_name='Template to use')),
                ('enabled', models.BooleanField(default=True, help_text='Enabled', verbose_name='Enabled')),
                ('footer_text', models.CharField(blank=True, help_text='Footer text', max_length=150, verbose_name='Footer text')),
            ],
        ),
        migrations.AddConstraint(
            model_name='certificates',
            constraint=models.UniqueConstraint(fields=('key',), name='UNQ_certificates_key'),
        ),
    ]
