# Generated by Django 4.1.5 on 2023-02-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
