# Generated by Django 4.1.5 on 2023-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0003_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='period_type',
            field=models.CharField(default='A', help_text='Type of periodicity of document.', max_length=1, verbose_name='Period type'),
        ),
    ]
