# Generated by Django 4.1.5 on 2023-02-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0004_certificate_period_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='period_type',
        ),
        migrations.AddField(
            model_name='certificate',
            name='closed',
            field=models.BooleanField(default=True, help_text='The period must be closed.', verbose_name='Closing required'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cycle_type',
            field=models.CharField(choices=[('A', 'Annual'), ('S', 'Biannual'), ('T', 'Quarterly'), ('B', 'Bimonthly'), ('M', 'Monthly')], default='A', help_text='Type of periodicity of document.', max_length=1, verbose_name='Period type'),
        ),
    ]
