# Generated by Django 4.1.5 on 2023-02-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0005_remove_certificate_period_type_certificate_closed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='legend',
            new_name='body_text',
        ),
    ]
