# Generated by Django 4.1.5 on 2023-02-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasis_certs', '0008_certificate_customer_type_alter_certificate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='signed',
            field=models.BooleanField(default=False, help_text='The document require to be signed', verbose_name='Sign required'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cycle_type',
            field=models.CharField(choices=[('A', 'Annual'), ('S', 'Biannual'), ('T', 'Quarterly'), ('B', 'Bimonthly'), ('M', 'Monthly'), ('N', 'None')], default='A', help_text='Type of periodicity of document.', max_length=1, verbose_name='Period type'),
        ),
    ]
