
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-28T19:25:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d373aa85c9c8f5b71bfbb2c3a5732c93a9498c6f",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
