from info import (welcome,how)
from function import (GetCityNumFromLiepin,
                      GetIpPool,
                      GetCityNumFromBossZhiPing,
                      GetCityNameFromLiepin,
                      YesOrNot,
                      CheckIp,
                      IntoZip,
                      ZipOut,
                      SendEmail,
                      GetEmail,
                      ProgressBar,
                      GetPlateSon,
                      GetPlateInfo,
                      MergeTable,
                      ChoiceColumn)