# Generated by Django 3.2.19 on 2023-06-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('newrelic_plugin_agent', '0001_initial'),
                ('newrelic_plugin_agent', '0002_migrate_jsonfield')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelicComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('last_pushed_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewRelicMetricTimeslice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=256)),
                ('values', models.JSONField()),
                ('new_relic_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_timeslices', to='newrelic_plugin_agent.newreliccomponent')),
            ],
            options={
                'unique_together': {('new_relic_component', 'guid')},
            },
        ),
    ]
