# Generated by Django 4.0.10 on 2023-06-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrelic_plugin_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrelicmetrictimeslice',
            name='values',
            field=models.JSONField(),
        ),
    ]
