# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/abc/dfds/00_meta.ipynb.

# %% auto 0
__all__ = ['MetaDataFrameDataset']

# %% ../../../nbs/abc/dfds/00_meta.ipynb 3
from abc import ABCMeta, abstractmethod
from dataclasses import dataclass, field

from beartype.typing import (
    Tuple, Union, List, 
)

# %% ../../../nbs/abc/dfds/00_meta.ipynb 4
from ...types import DataFrame

# %% ../../../nbs/abc/dfds/00_meta.ipynb 6
class MetaDataFrameDataset(ABCMeta):
    __args__: Tuple[DataFrame, ...]

    def __instancecheck__(cls, instance):
        return hasattr(instance, 'df')
    
    @abstractmethod
    def __getitem__(self, idx: Union[int, slice]) -> List:
        pass
