
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-02T15:51:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c16689b1c5c0b20d0009c05cc43f9d0a4ccd225",
 "version": "12.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
