# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: private_protocol/tongos_protocol/media/nlp/tongos_media_llm_res.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='private_protocol/tongos_protocol/media/nlp/tongos_media_llm_res.proto',
  package='bigai.tongos.media.nlp',
  syntax='proto3',
  serialized_options=b'Z\030tongos.org/api/media/nlp',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nEprivate_protocol/tongos_protocol/media/nlp/tongos_media_llm_res.proto\x12\x16\x62igai.tongos.media.nlp\"2\n\x0bLLMRESMedia\x1a#\n\tChunkData\x12\x16\n\x06output\x18\x01 \x01(\tR\x06outputB\x1aZ\x18tongos.org/api/media/nlpb\x06proto3'
)




_LLMRESMEDIA_CHUNKDATA = _descriptor.Descriptor(
  name='ChunkData',
  full_name='bigai.tongos.media.nlp.LLMRESMedia.ChunkData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='bigai.tongos.media.nlp.LLMRESMedia.ChunkData.output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='output', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=147,
)

_LLMRESMEDIA = _descriptor.Descriptor(
  name='LLMRESMedia',
  full_name='bigai.tongos.media.nlp.LLMRESMedia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_LLMRESMEDIA_CHUNKDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=147,
)

_LLMRESMEDIA_CHUNKDATA.containing_type = _LLMRESMEDIA
DESCRIPTOR.message_types_by_name['LLMRESMedia'] = _LLMRESMEDIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LLMRESMedia = _reflection.GeneratedProtocolMessageType('LLMRESMedia', (_message.Message,), {

  'ChunkData' : _reflection.GeneratedProtocolMessageType('ChunkData', (_message.Message,), {
    'DESCRIPTOR' : _LLMRESMEDIA_CHUNKDATA,
    '__module__' : 'private_protocol.tongos_protocol.media.nlp.tongos_media_llm_res_pb2'
    # @@protoc_insertion_point(class_scope:bigai.tongos.media.nlp.LLMRESMedia.ChunkData)
    })
  ,
  'DESCRIPTOR' : _LLMRESMEDIA,
  '__module__' : 'private_protocol.tongos_protocol.media.nlp.tongos_media_llm_res_pb2'
  # @@protoc_insertion_point(class_scope:bigai.tongos.media.nlp.LLMRESMedia)
  })
_sym_db.RegisterMessage(LLMRESMedia)
_sym_db.RegisterMessage(LLMRESMedia.ChunkData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
