
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-27T10:36:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "837a8428a1459f24ac5de89ad8c7a1c98cde6514",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
