# Generated by Django 2.2.3 on 2022-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_notifications', 'View notifications'), ('add_notifications', 'Add notifications'), ('change_notifications', 'Edit notifications'), ('delete_notifications', 'Delete notifications'), ('view_topics', 'View topics'), ('add_topics', 'Add topics'), ('change_topics', 'Edit topics'), ('delete_topics', 'Delete topics')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
