
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-06-29T22:27:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f71b2f081db0c865e1a2e22b436b1bc42cfe36a8",
 "version": "0.4.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
