
ALPHAVANTAGE = 'ALPHAVANTAGE'
QUANDL = 'QUANDL'
POSTGRES = 'POSTGRES'

# available methods / tables
REFRESH_SYMBOL = 'REFRESH_SYMBOL'
SYMBOL = 'SYMBOL'
EXCHANGE = 'EXCHANGE'
BASE_SYMBOL = 'BASE_SYMBOL'
QUOTE_SYMBOL = 'QUOTE_SYMBOL'

RAW = 'RAW'

# db schema
TABLE = 'tb_'
