# coding: utf-8

"""
    Zadara VPSA Storage Array REST API

     # Overview  This document outlines the methods available for administrating your Zadara Storage VPSA&#8482;. The Zadara Storage Array REST API   supports form-encoded, JSON, and XML requests, and can return either JSON or XML responses.  ## Usage  The majority of the APIs available require authentication which requires an API token to use. You can retrieve this token through the   Users section of your VPSA, or through the API using the \"Return a user's access key\" API in the Users Section below.  ## Authentication Methods  The authentication token can be passed either through the access_key parameter inside of the body of the REST API request, or   through the X-Access-Key header.  ## Timeouts  By default, all operations that don't complete within five seconds will return a message informing you that the action may take some  time to complete. When using the API, this can cause some actions, such as large volume creation, to be undesirably asynchronous.  You can specify your own timeout with the timeout parameter, in seconds, and a timeout value of -1 specifies an infinite timeout.  ## Specific Fields For Product  Some of the fields/actions used in the API should be used only for a specific product. The following tags are used to mark which   product responds to the fields/actions  VPSA Flash Array - All Flash Array VPSA  VPSA Storage Array - Hybrid VPSA  ## Questions  If you have any questions or need support involving the REST API, please contact for assistance.   # noqa: E501

    OpenAPI spec version: 23.03.1
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from Vpsa.configuration import Configuration


class InlineResponse20081ResponseVolumes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'display_name': 'str',
        'created_at': 'str',
        'modified_at': 'str',
        'data_type': 'str',
        'pool_name': 'str'
    }

    attribute_map = {
        'name': 'name',
        'display_name': 'display_name',
        'created_at': 'created_at',
        'modified_at': 'modified_at',
        'data_type': 'data_type',
        'pool_name': 'pool_name'
    }

    def __init__(self, name=None, display_name=None, created_at=None, modified_at=None, data_type=None, pool_name=None, _configuration=None):  # noqa: E501
        """InlineResponse20081ResponseVolumes - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._display_name = None
        self._created_at = None
        self._modified_at = None
        self._data_type = None
        self._pool_name = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if display_name is not None:
            self.display_name = display_name
        if created_at is not None:
            self.created_at = created_at
        if modified_at is not None:
            self.modified_at = modified_at
        if data_type is not None:
            self.data_type = data_type
        if pool_name is not None:
            self.pool_name = pool_name

    @property
    def name(self):
        """Gets the name of this InlineResponse20081ResponseVolumes.  # noqa: E501


        :return: The name of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20081ResponseVolumes.


        :param name: The name of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def display_name(self):
        """Gets the display_name of this InlineResponse20081ResponseVolumes.  # noqa: E501


        :return: The display_name of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this InlineResponse20081ResponseVolumes.


        :param display_name: The display_name of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def created_at(self):
        """Gets the created_at of this InlineResponse20081ResponseVolumes.  # noqa: E501


        :return: The created_at of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this InlineResponse20081ResponseVolumes.


        :param created_at: The created_at of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def modified_at(self):
        """Gets the modified_at of this InlineResponse20081ResponseVolumes.  # noqa: E501


        :return: The modified_at of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :rtype: str
        """
        return self._modified_at

    @modified_at.setter
    def modified_at(self, modified_at):
        """Sets the modified_at of this InlineResponse20081ResponseVolumes.


        :param modified_at: The modified_at of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :type: str
        """

        self._modified_at = modified_at

    @property
    def data_type(self):
        """Gets the data_type of this InlineResponse20081ResponseVolumes.  # noqa: E501


        :return: The data_type of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this InlineResponse20081ResponseVolumes.


        :param data_type: The data_type of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :type: str
        """

        self._data_type = data_type

    @property
    def pool_name(self):
        """Gets the pool_name of this InlineResponse20081ResponseVolumes.  # noqa: E501


        :return: The pool_name of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :rtype: str
        """
        return self._pool_name

    @pool_name.setter
    def pool_name(self, pool_name):
        """Sets the pool_name of this InlineResponse20081ResponseVolumes.


        :param pool_name: The pool_name of this InlineResponse20081ResponseVolumes.  # noqa: E501
        :type: str
        """

        self._pool_name = pool_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20081ResponseVolumes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20081ResponseVolumes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20081ResponseVolumes):
            return True

        return self.to_dict() != other.to_dict()
