/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sketcher::SketchObject
 */
export interface ISketchObject {
  /**
   * The attachment offset
   */
  AttachmentOffset: {
    /**
     * Position of the Placement
     */
    Position: number[];
    /**
     * Axis of the Placement
     */
    Axis: number[];
    /**
     * Angle of the Placement
     */
    Angle: number;
  };
  /**
   * The geometry list
   */
  Geometry: (IGeomCircle | IGeomLineSegment)[];
  /**
   * Placement of the box
   */
  Placement?: {
    /**
     * Position of the Placement
     */
    Position: number[];
    /**
     * Axis of the Placement
     */
    Axis: number[];
    /**
     * Angle of the Placement
     */
    Angle: number;
  };
}
/**
 * Part::GeomCircle
 */
export interface IGeomCircle {
  /**
   * Geometry type
   */
  TypeId: "Part::GeomCircle";
  /**
   * CenterX
   */
  CenterX: number;
  /**
   * CenterY
   */
  CenterY: number;
  /**
   * CenterZ
   */
  CenterZ: number;
  /**
   * NormalX
   */
  NormalX: number;
  /**
   * NormalY
   */
  NormalY: number;
  /**
   * NormalZ
   */
  NormalZ: number;
  /**
   * AngleXU
   */
  AngleXU: number;
  /**
   * Radius
   */
  Radius: number;
}
/**
 * Part::GeomLineSegment
 */
export interface IGeomLineSegment {
  /**
   * Geometry type
   */
  TypeId: "Part::GeomLineSegment";
  /**
   * StartX
   */
  StartX: number;
  /**
   * StartY
   */
  StartY: number;
  /**
   * StartZ
   */
  StartZ: number;
  /**
   * EndX
   */
  EndX: number;
  /**
   * EndY
   */
  EndY: number;
  /**
   * EndZ
   */
  EndZ: number;
}
