# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_types.ipynb.

# %% auto 0
__all__ = ['Module', 'Loader', 'ModuleSpec', 'VariableDict', 'FallbackType', 'ImpItemsType', 'ImpSubSpecType']

# %% ../nbs/00_types.ipynb 3
import types, importlib

from importlib.abc import Loader
from importlib.machinery import ModuleSpec

from typing import Optional, Dict, Any, TypeAlias, Union, ClassVar, List, Tuple

# %% ../nbs/00_types.ipynb 5
Module: TypeAlias = types.ModuleType

Loader: TypeAlias = importlib.abc.Loader

ModuleSpec: TypeAlias = importlib.machinery.ModuleSpec

VariableDict: TypeAlias = Dict[str, Any]

FallbackType: TypeAlias = Optional[Union['Fallbacks', VariableDict]]

ImpItemsType: TypeAlias = Optional[List['ImpItem']]

ImpSubSpecType : TypeAlias = Optional[List['ImpSubSpec']]
